Repository Xplatforms/mbseedkey, pull requests merged in 2020-10, with the labels that each got.

#9 custom values for access level, seed and key length
  ECUPage.qml
  MainPage.qml
  ecuseedkeydll.cpp
  ecuseedkeydll.h
Labels: hacktoberhest

#10 First fully working release
  ECUPage.qml
  ecuseedkeydll.cpp
  ecuseedkeydll.h
  exutils.cpp
  exutils.h
Labels: enhancement, hacktoberhest

#11 Disable select button if no dll selected. Update inputMask
  ECUPage.qml
  MainPage.qml
  exutils.cpp
Labels: hacktoberfest-accepted
